version: '3'
services:
  jenkins:
    image: jenkins-with-docker:latest
    user: root
    volumes:
      - /Users/mini14/File/jenkins_home_backup:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock   # 이 부분이 필수
    ports:
      - "8080:8080"
      - "50000:50000"
volumes:
  jenkins_home_backup:
